# -*- coding: utf-8 -*-
"""Part4_Lazy Classifier .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k7rjEp7tQeSxl4zNQQ2tighV3_JYMnX3

#Lazy Predict Classifier without any sampling stratigies.
This step helped to get rough idea about the algorithm which could be used for the refined model.
"""

!pip install lazypredict

import pandas as pd
df=pd.read_csv('Final_full_Top20.csv') #Use your input dataset befoe spliting
df

df.isna().sum()
df.dropna(inplace=True)

X = df.drop('BioactivityClass', axis=1)
Y = df['BioactivityClass']

Y = df['BioactivityClass']
Y

!pip install dask[dataframe]

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from lazypredict.Supervised import LazyClassifier
import warnings
warnings.filterwarnings("ignore")

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, stratify=Y,random_state=100)

X_train.shape, Y_train.shape

X_test.shape, Y_test.shape

X_train.to_csv("MACCS_X_train_set.csv", index=False)
X_test.to_csv("MACCS_X_test_set.csv", index=False)
Y_train.to_csv("MACCS_Y_train_set.csv", index=False)
Y_test.to_csv("MACCS_Y_test_set.csv", index=False)

"""#Plotting PCA for train and test set"""

from sklearn.decomposition import PCA
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

# The 'Name' column does not exist in X_train and X_test, so dropping it is unnecessary.
X_train_pca = X_train
X_test_pca = X_test

# Fit PCA
pca = PCA(n_components=3)
pca_train = pca.fit_transform(X_train_pca)
pca_test  = pca.transform(X_test_pca)

# 3D Plot
fig = plt.figure(figsize=(12,12))
ax = fig.add_subplot(111, projection='3d')

ax.scatter(pca_train[:,0], pca_train[:,1], pca_train[:,2], c='darkblue', s=120, alpha=1.0, label='Train set')
ax.scatter(pca_test[:,0],  pca_test[:,1],  pca_test[:,2],  c='limegreen', s=120, alpha=1.0, label='Test set')

ax.tick_params(axis='x', labelsize=16)
ax.tick_params(axis='y', labelsize=16)
ax.tick_params(axis='z', labelsize=16)

ax.set_xlabel("PC1", fontsize=16)
ax.set_ylabel("PC2", fontsize=16)
ax.set_zlabel("PC3", fontsize=16)

ax.legend()
plt.tight_layout()
plt.savefig("PCA_Train_Test_3D_new.png", dpi=300, bbox_inches='tight')
plt.show()

"""#Building models with LazyClassifier"""

clf = LazyClassifier(verbose=0,ignore_warnings=True)
models, predictions = clf.fit(X_train_pca, X_test_pca, Y_train, Y_test)
models

! zip SIRT1_lazyclassifier.zip *.csv *.png